init cube yyyywrbwbrowggbogwrryorwooyoygbbygbrogbboogggbwrryrwww
run YGO_Cubie.cmd
init cube wogbwgywyoyoygwggybbrgrooywgrwbbwbrbowbrooyrrggroyywbr
run YGO_Cubie.cmd
init cube gobowwyryrgoygrbyobggwrbwgyobwrbyrogrwyoogwbogwbrybwyr
run YGO_Cubie.cmd
init cube yyrowbwwybygogrgwwrggbrbobboyywbrryrbrogogyowbowrygowg
run YGO_Cubie.cmd
init cube robrwbgoobbyygwrrwrgygryowggoybboogroyywogwwwbbwyyrgrb
run YGO_Cubie.cmd
init cube wwbrwoogbrbgrggbwowwyorrbyroywwbyyogrbgbogyrrwggoybyyo
run YGO_Cubie.cmd
init cube ggobwywowwrrrggbbobboyrgbgrgbyrbwyyrgorroybwywwgwyoooy
run YGO_Cubie.cmd
init cube ggyrwogbbyyybgowowrrybryrgboybbbrrwwrwogowgrbgywgyoowo
run YGO_Cubie.cmd
init cube bybbworyyrrgygboggybgwrwooroyrrbggwyyrwoogbwwwbwrygboo
run YGO_Cubie.cmd
init cube gowbwgbgrryrwgoowwyywwrwbrygobbbbbrgoyyrogyogrgoryywbo
run YGO_Cubie.cmd
init cube grbrwybobwwybggwwgowryroooyyrwgbwoygrbrboyrgbwbggyoory
run YGO_Cubie.cmd
init cube ooowwgbyygrryggwgryborrogbwbowwbwgbybyygorgwrwroyyobbr
run YGO_Cubie.cmd
init cube yrwbwgoobbygwgwygrwyogrbgwrwrrrbyyrobwogobgobwogoyyrby
run YGO_Cubie.cmd
init cube boyrwggwbywrrgorygwoygryorbowgbbywrgobrgoyrwbwbooygwby
run YGO_Cubie.cmd
init cube wwwywroogbggwgorogwbowrbwryygbybyrbyorroogbbgrybgyrywo
run YGO_Cubie.cmd
init cube yrybwgboybwoygwgbgwbborgwryrorybrowwgyowoobgwrbgyygorr
run YGO_Cubie.cmd
init cube borgwbbwgoyrggobroyoybrggyorrbwbgwywwyyroorwoybgwyrwbg
run YGO_Cubie.cmd
init cube gbybwgyywryoygrgwbboggrbrrwrobrbygworwygorboowwooygybw
run YGO_Cubie.cmd
init cube ggygwrogoryyrgbroogwgyrbbrrwyorbowoyboywogrwwwwbbyygbb
run YGO_Cubie.cmd
init cube bygbwybybywoggowoywgwyrogrwrrobbbrrbybrrowogorwgwyggoy
run YGO_Cubie.cmd
init cube yggrwowowbwoygwryrggborgwgrobowbygwryyoroobbgbrwbybyry
run YGO_Cubie.cmd
init cube ryrgwryywyrowgwrrybbbbryoowobbobwrowwgggorgoygggyywbbo
run YGO_Cubie.cmd
init cube ywwgwrywrrogbgyrorogworwybbgybrbyoooobbgoywrbgrywybwgg
run YGO_Cubie.cmd
init cube oywrwbwrgybobgbrooggywrwbrgryggbgywbrobyoorgywyowyrbow
run YGO_Cubie.cmd
init cube grwbwyrwyrowogrwyggbbgryyrwrrrobgowbbbyoowoboowbgyggyy
run YGO_Cubie.cmd
init cube wwwgwrgryrrwggbbywoboyrwbgybybobooorobgbooyrrrwggyyywg
run YGO_Cubie.cmd
init cube ggowwggyrybwwgwrbborgrrrogwyywbbobgwbroyoorbyyoryywbog
run YGO_Cubie.cmd
init cube orgowwryybbwggywrbgrooryygwboogbbgrrygwyooybrrwobywbwg
run YGO_Cubie.cmd
init cube goygwbgwoyrrygyyrowowrrbywrborwbrwgogyowobwgbbgbbyyrog
run YGO_Cubie.cmd
init cube owrowgrbrggbygowybwrwbrooyygwgwbyrwoyryrobbroyobgybggw
run YGO_Cubie.cmd
init cube rrwgwwyrryogbgyoyyogwbrrrwggorybwoobbbggoowrbbbwgyyywo
run YGO_Cubie.cmd
init cube robwwyggogrobgrowyywwgrgroobgwobbwrrrywroyyobbwgbyyybg
run YGO_Cubie.cmd
init cube bywwwyoroyggggwrbgwgbrrowywyobbbbbooorrwoygggrbrrywyoy
run YGO_Cubie.cmd
init cube wyrrwyoggbwybgrogbgrrbrgwwbwogybgywyyrrooybbgobrwyowoo
run YGO_Cubie.cmd
init cube rryywgoyywrwrgogwwborgrwggbgrbobbobgrwbwobyyroyygyowbo
run YGO_Cubie.cmd
init cube grrywbrrborbygbygowgoorryygwwybbywwgbwwboorggbgroyoowy
run YGO_Cubie.cmd
init cube oywgwbowgbwgbgobrywoybrrowbrrrgbryyrbgwyoygoygbrwyoogw
run YGO_Cubie.cmd
init cube rogwwbggobgorggbowyowyrgbrrbrwrboywwobywoyrbyrwgyyboyg
run YGO_Cubie.cmd
init cube oyygwgobwbogwgoowgwyryrowgrbrrbbrbryggwyoroobrwybybywg
run YGO_Cubie.cmd
init cube ogywwyoybwoyrgbogggbyrrgwbroobobgwbrrrgyowyrwrwbwyobyg
run YGO_Cubie.cmd
init cube oroowygwbbwwoggrybobworrywyrgyybgbgwgbwwobrygrrobyryog
run YGO_Cubie.cmd
init cube rorbwygrgbywbgrorrogrbryywbwobgbwwyywbyoowboyggowyrggo
run YGO_Cubie.cmd
init cube ygyrwowyogygogyrrbrgbbroygwybggbwoboowrooywwbrrbbywwrg
run YGO_Cubie.cmd
init cube ggbwwwbwyyowyggwyrrrbrrwyoorbogbrwrowooyooyyggbggybrbb
run YGO_Cubie.cmd
init cube wgyyworybgowwgrygwgrygrrogwobrbbbbrygooyooowbbyrwywrbg
run YGO_Cubie.cmd
init cube wwwywgyboboboggybyrywwrwoygbrorbbwyogoroogyrrggrwyrgbb
run YGO_Cubie.cmd
init cube bgoywowbryggrggoyorrbrrggwbwwgwbwwbyworroygybybobyoyor
run YGO_Cubie.cmd
init cube yrwrwowbobybogwbogorgbrgygrwyrwbyyrwbwobogroroygbygywg
run YGO_Cubie.cmd
init cube bwrowbwgwwgoogwybrgrgrrywgorogobygwryborowbyobyyrygbby
run YGO_Cubie.cmd
init cube rbrbwgyrrbyroggowbgwwyrbooygobrbrowowoygowbrgyyggybwyw
run YGO_Cubie.cmd
init cube byyrwgwbrrwbogygggorwbrgobbgyoobyywgbrwoowyoywwrrygrbo
run YGO_Cubie.cmd
init cube wogwwwyrwrobrgggbyryrorbgobbborbywgyyyggogbrwrboyywowo
run YGO_Cubie.cmd
init cube wrgwwobywboyygrobgoobgrrrwgobwybowwbowrgobyyyybrrygggr
run YGO_Cubie.cmd
init cube wwrrwbyobgwoygygyobwrorrbgyyrbgbyoogwborogrgrwogbybwwy
run YGO_Cubie.cmd
init cube rwyywwwggyrrbgobrybwrbryryywooobbooobrgyowwrobgggygwbg
run YGO_Cubie.cmd
init cube bwwowgbygygyrgbgyrobworogwboyrybrwrybgrwogooywborybrwg
run YGO_Cubie.cmd
init cube bwobwgrworowogoyrogggyrgyrbwryobrwyrgbwwowyybbboyygrbg
run YGO_Cubie.cmd
init cube ogwowgwrbygbbgwooooyrbrygwgyrrbbwwyrbwbroryogyoryygwbg
run YGO_Cubie.cmd
init cube rbrywybogwrowgrgoywyobrgbbgygyobgwggbobworoyyowrwyrrbw
run YGO_Cubie.cmd
init cube ryygwobbbbyygggrywooorrbrogwwrrbworogoybowgybggwrywwby
run YGO_Cubie.cmd
init cube yyrbwwwgyrwbogwgbrororroyggbobybgyowwbbwoggrrgyorybwyo
run YGO_Cubie.cmd
init cube gogrwwbrgrywrgbobwrbrorggyowoowbgyrbygyyowyowobbwygbyr
run YGO_Cubie.cmd
init cube wgyrwroyrrywogwggbbbborwybgwgrgbbowygogroybborowyyrywo
run YGO_Cubie.cmd
init cube ogroworbrbwwbggorogwbwryyoywyybbroyrbywwooyrgbgggyrwbg
run YGO_Cubie.cmd
init cube rowbwyobwbryygrbwrgobwryygworggbggbyryyoobbwwgrooywrgo
run YGO_Cubie.cmd
init cube grbrwybgrogoygbyggwwgrrgyrbyoroborbryywwobgboowwyywbow
run YGO_Cubie.cmd
init cube rwrowwwogggbrgbgrrowowrgbywygbrbygybwrwoobobyyboyygroy
run YGO_Cubie.cmd
init cube orggwbrywyowbgrbobgrrwrwyyobroobbwgyygbyowgoorggbywwyr
run YGO_Cubie.cmd
init cube ggbrworbwwwywgbygbbyorroogwgboybrbwrwrryobyggyyroyoowg
run YGO_Cubie.cmd
init cube wgrrwoobroyyogorrogwwgrowrygybwbybrywybbobrgggwogybywb
run YGO_Cubie.cmd
init cube boggwyogyoogogwrbgwwbrryyrbrryobyrrwrwygobobwobwwyggyb
run YGO_Cubie.cmd
init cube bbgywbbroroowgwyygwwgorwygywoybbobrwrywgogrgbororybryg
run YGO_Cubie.cmd
init cube wroywboybgoybgwyyrggogrogrywwbwbrrgrywogorwbrwybbyogob
run YGO_Cubie.cmd
init cube orrgwwrrgbybggyrrywgwbrogyyogyybwbwgbwwbooybwrrobyogoo
run YGO_Cubie.cmd
init cube gbygwogbgwywogwwwborogroogwybrwbybwbgyrroyygbyrrryboor
run YGO_Cubie.cmd
init cube ywwbwyybogoooggggrbwgyrbwbbwrbybgywyorrooyoorbrrrygwwg
run YGO_Cubie.cmd
init cube ywogwobrggywygoyrbryowrwwwwygbgbyrogybrbooorborgbybrgw
run YGO_Cubie.cmd
init cube ggwywwoogobybgooyrgwygrrbbbrbgybgwgwrwwyorbwbyoooyryrr
run YGO_Cubie.cmd
init cube rroywbrgoggywgygwwbowrrobbybrbybbgbgygwyogooororrywyww
run YGO_Cubie.cmd
init cube rybgwoyyyyobogrwrbrbogrbwwrbwwwbrgbgrggyobyooogwwyrgyo
run YGO_Cubie.cmd
init cube rwobwyrgbyoywgogygbrogrbyrbwobybbrrwyrgwogrwwoywgyboog
run YGO_Cubie.cmd
init cube wggywbygyroorgbrwgbybrrwoobroorbbrgbyrgwoywbgwwwgyoyyo
run YGO_Cubie.cmd
init cube owgywbybrbbgbggbrgowbwryrywwrwobrroborwgooygyyggyywoor
run YGO_Cubie.cmd
init cube rowywgbbrgbrggwbyoyrbgrrgrywoowbwgwogywboyboyygrryoobw
run YGO_Cubie.cmd
init cube gwggwroobrrybgwobogwwgrobyrryrbbbbgowryyowyogwoyryywgb
run YGO_Cubie.cmd
init cube rbgywgoobgobbggrorywrorbyrwyywrbyorooywrowgwbggbbywwgy
run YGO_Cubie.cmd
init cube ygowwwrywbbyrgrrowbgbgryrroorgbbygorwwooobwoggyywybygb
run YGO_Cubie.cmd
init cube ogwrworygyygygrbwrygwwrowooobgwbrgrorwbbobborbgybygyyw
run YGO_Cubie.cmd
init cube bbgwwyogrygbbgyorryogorowggyrowbgwwwyyryowobgbrrbyrwob
run YGO_Cubie.cmd
init cube ogrbwbobbbogggbowowwwrrggywrygobyrgbyywoowyobyrgryrywr
run YGO_Cubie.cmd
init cube goybwwwywyobrgybbgoorbrwryrbrbbbgggwrwowoggoyyrwryyogo
run YGO_Cubie.cmd
init cube yrgwwyyrgbobggwgworbwrrwbyrooogbyyowyyoborbgrwggbybwor
run YGO_Cubie.cmd
init cube yoobwrybbgogbgoogwoyrgrwrobyygrbgrbowwrrowbwbgywyyrygw
run YGO_Cubie.cmd
init cube grorwoybywygbgywbgorborwrgrrwbgbowboywrgoybgoyrbwyogyw
run YGO_Cubie.cmd
init cube yowowwgoobwyggbbgbrbyyrrrybgbogbrybrgyowowgyowgroyrwrw
run YGO_Cubie.cmd
init cube gwybwrrobywyogywyybwwrrgbbgrbrobbogwggoooyrwboywgyrorg
run YGO_Cubie.cmd
init cube gyowwogboyoywggbbbrowyrbrrwbybrbrgggyrowogwwrwgoyyoybr
run YGO_Cubie.cmd
init cube woobworrroowbgwwoygbybrybrrbyygbwwwygwbgoygroogbgyrgyr
run YGO_Cubie.cmd
init cube robbwobwrwrrygywyoygwrrogbogyywbgwrrobboobywbywggygorg
run YGO_Cubie.cmd
init cube orogwbgwbgowggrbbrogyyryggyoowobbgwbbwywoyybwwrryyorrr
run YGO_Cubie.cmd

