init cube yyyywrbwbrowggbogwrryorwooyoygbbygbrogbboogggbwrryrwww
run WGR_Cubie.cmd
init cube wogbwgywyoyoygwggybbrgrooywgrwbbwbrbowbrooyrrggroyywbr
run WGR_Cubie.cmd
init cube gobowwyryrgoygrbyobggwrbwgyobwrbyrogrwyoogwbogwbrybwyr
run WGR_Cubie.cmd
init cube yyrowbwwybygogrgwwrggbrbobboyywbrryrbrogogyowbowrygowg
run WGR_Cubie.cmd
init cube robrwbgoobbyygwrrwrgygryowggoybboogroyywogwwwbbwyyrgrb
run WGR_Cubie.cmd
init cube wwbrwoogbrbgrggbwowwyorrbyroywwbyyogrbgbogyrrwggoybyyo
run WGR_Cubie.cmd
init cube ggobwywowwrrrggbbobboyrgbgrgbyrbwyyrgorroybwywwgwyoooy
run WGR_Cubie.cmd
init cube ggyrwogbbyyybgowowrrybryrgboybbbrrwwrwogowgrbgywgyoowo
run WGR_Cubie.cmd
init cube bybbworyyrrgygboggybgwrwooroyrrbggwyyrwoogbwwwbwrygboo
run WGR_Cubie.cmd
init cube gowbwgbgrryrwgoowwyywwrwbrygobbbbbrgoyyrogyogrgoryywbo
run WGR_Cubie.cmd
init cube grbrwybobwwybggwwgowryroooyyrwgbwoygrbrboyrgbwbggyoory
run WGR_Cubie.cmd
init cube ooowwgbyygrryggwgryborrogbwbowwbwgbybyygorgwrwroyyobbr
run WGR_Cubie.cmd
init cube yrwbwgoobbygwgwygrwyogrbgwrwrrrbyyrobwogobgobwogoyyrby
run WGR_Cubie.cmd
init cube boyrwggwbywrrgorygwoygryorbowgbbywrgobrgoyrwbwbooygwby
run WGR_Cubie.cmd
init cube wwwywroogbggwgorogwbowrbwryygbybyrbyorroogbbgrybgyrywo
run WGR_Cubie.cmd
init cube yrybwgboybwoygwgbgwbborgwryrorybrowwgyowoobgwrbgyygorr
run WGR_Cubie.cmd
init cube borgwbbwgoyrggobroyoybrggyorrbwbgwywwyyroorwoybgwyrwbg
run WGR_Cubie.cmd
init cube gbybwgyywryoygrgwbboggrbrrwrobrbygworwygorboowwooygybw
run WGR_Cubie.cmd
init cube ggygwrogoryyrgbroogwgyrbbrrwyorbowoyboywogrwwwwbbyygbb
run WGR_Cubie.cmd
init cube bygbwybybywoggowoywgwyrogrwrrobbbrrbybrrowogorwgwyggoy
run WGR_Cubie.cmd
init cube yggrwowowbwoygwryrggborgwgrobowbygwryyoroobbgbrwbybyry
run WGR_Cubie.cmd
init cube ryrgwryywyrowgwrrybbbbryoowobbobwrowwgggorgoygggyywbbo
run WGR_Cubie.cmd
init cube ywwgwrywrrogbgyrorogworwybbgybrbyoooobbgoywrbgrywybwgg
run WGR_Cubie.cmd
init cube oywrwbwrgybobgbrooggywrwbrgryggbgywbrobyoorgywyowyrbow
run WGR_Cubie.cmd
init cube grwbwyrwyrowogrwyggbbgryyrwrrrobgowbbbyoowoboowbgyggyy
run WGR_Cubie.cmd
init cube wwwgwrgryrrwggbbywoboyrwbgybybobooorobgbooyrrrwggyyywg
run WGR_Cubie.cmd
init cube ggowwggyrybwwgwrbborgrrrogwyywbbobgwbroyoorbyyoryywbog
run WGR_Cubie.cmd
init cube orgowwryybbwggywrbgrooryygwboogbbgrrygwyooybrrwobywbwg
run WGR_Cubie.cmd
init cube goygwbgwoyrrygyyrowowrrbywrborwbrwgogyowobwgbbgbbyyrog
run WGR_Cubie.cmd
init cube owrowgrbrggbygowybwrwbrooyygwgwbyrwoyryrobbroyobgybggw
run WGR_Cubie.cmd
init cube rrwgwwyrryogbgyoyyogwbrrrwggorybwoobbbggoowrbbbwgyyywo
run WGR_Cubie.cmd
init cube robwwyggogrobgrowyywwgrgroobgwobbwrrrywroyyobbwgbyyybg
run WGR_Cubie.cmd
init cube bywwwyoroyggggwrbgwgbrrowywyobbbbbooorrwoygggrbrrywyoy
run WGR_Cubie.cmd
init cube wyrrwyoggbwybgrogbgrrbrgwwbwogybgywyyrrooybbgobrwyowoo
run WGR_Cubie.cmd
init cube rryywgoyywrwrgogwwborgrwggbgrbobbobgrwbwobyyroyygyowbo
run WGR_Cubie.cmd
init cube grrywbrrborbygbygowgoorryygwwybbywwgbwwboorggbgroyoowy
run WGR_Cubie.cmd
init cube oywgwbowgbwgbgobrywoybrrowbrrrgbryyrbgwyoygoygbrwyoogw
run WGR_Cubie.cmd
init cube rogwwbggobgorggbowyowyrgbrrbrwrboywwobywoyrbyrwgyyboyg
run WGR_Cubie.cmd
init cube oyygwgobwbogwgoowgwyryrowgrbrrbbrbryggwyoroobrwybybywg
run WGR_Cubie.cmd
init cube ogywwyoybwoyrgbogggbyrrgwbroobobgwbrrrgyowyrwrwbwyobyg
run WGR_Cubie.cmd
init cube oroowygwbbwwoggrybobworrywyrgyybgbgwgbwwobrygrrobyryog
run WGR_Cubie.cmd
init cube rorbwygrgbywbgrorrogrbryywbwobgbwwyywbyoowboyggowyrggo
run WGR_Cubie.cmd
init cube ygyrwowyogygogyrrbrgbbroygwybggbwoboowrooywwbrrbbywwrg
run WGR_Cubie.cmd
init cube ggbwwwbwyyowyggwyrrrbrrwyoorbogbrwrowooyooyyggbggybrbb
run WGR_Cubie.cmd
init cube wgyyworybgowwgrygwgrygrrogwobrbbbbrygooyooowbbyrwywrbg
run WGR_Cubie.cmd
init cube wwwywgyboboboggybyrywwrwoygbrorbbwyogoroogyrrggrwyrgbb
run WGR_Cubie.cmd
init cube bgoywowbryggrggoyorrbrrggwbwwgwbwwbyworroygybybobyoyor
run WGR_Cubie.cmd
init cube yrwrwowbobybogwbogorgbrgygrwyrwbyyrwbwobogroroygbygywg
run WGR_Cubie.cmd
init cube bwrowbwgwwgoogwybrgrgrrywgorogobygwryborowbyobyyrygbby
run WGR_Cubie.cmd
init cube rbrbwgyrrbyroggowbgwwyrbooygobrbrowowoygowbrgyyggybwyw
run WGR_Cubie.cmd
init cube byyrwgwbrrwbogygggorwbrgobbgyoobyywgbrwoowyoywwrrygrbo
run WGR_Cubie.cmd
init cube wogwwwyrwrobrgggbyryrorbgobbborbywgyyyggogbrwrboyywowo
run WGR_Cubie.cmd
init cube wrgwwobywboyygrobgoobgrrrwgobwybowwbowrgobyyyybrrygggr
run WGR_Cubie.cmd
init cube wwrrwbyobgwoygygyobwrorrbgyyrbgbyoogwborogrgrwogbybwwy
run WGR_Cubie.cmd
init cube rwyywwwggyrrbgobrybwrbryryywooobbooobrgyowwrobgggygwbg
run WGR_Cubie.cmd
init cube bwwowgbygygyrgbgyrobworogwboyrybrwrybgrwogooywborybrwg
run WGR_Cubie.cmd
init cube bwobwgrworowogoyrogggyrgyrbwryobrwyrgbwwowyybbboyygrbg
run WGR_Cubie.cmd
init cube ogwowgwrbygbbgwooooyrbrygwgyrrbbwwyrbwbroryogyoryygwbg
run WGR_Cubie.cmd
init cube rbrywybogwrowgrgoywyobrgbbgygyobgwggbobworoyyowrwyrrbw
run WGR_Cubie.cmd
init cube ryygwobbbbyygggrywooorrbrogwwrrbworogoybowgybggwrywwby
run WGR_Cubie.cmd
init cube yyrbwwwgyrwbogwgbrororroyggbobybgyowwbbwoggrrgyorybwyo
run WGR_Cubie.cmd
init cube gogrwwbrgrywrgbobwrbrorggyowoowbgyrbygyyowyowobbwygbyr
run WGR_Cubie.cmd
init cube wgyrwroyrrywogwggbbbborwybgwgrgbbowygogroybborowyyrywo
run WGR_Cubie.cmd
init cube ogroworbrbwwbggorogwbwryyoywyybbroyrbywwooyrgbgggyrwbg
run WGR_Cubie.cmd
init cube rowbwyobwbryygrbwrgobwryygworggbggbyryyoobbwwgrooywrgo
run WGR_Cubie.cmd
init cube grbrwybgrogoygbyggwwgrrgyrbyoroborbryywwobgboowwyywbow
run WGR_Cubie.cmd
init cube rwrowwwogggbrgbgrrowowrgbywygbrbygybwrwoobobyyboyygroy
run WGR_Cubie.cmd
init cube orggwbrywyowbgrbobgrrwrwyyobroobbwgyygbyowgoorggbywwyr
run WGR_Cubie.cmd
init cube ggbrworbwwwywgbygbbyorroogwgboybrbwrwrryobyggyyroyoowg
run WGR_Cubie.cmd
init cube wgrrwoobroyyogorrogwwgrowrygybwbybrywybbobrgggwogybywb
run WGR_Cubie.cmd
init cube boggwyogyoogogwrbgwwbrryyrbrryobyrrwrwygobobwobwwyggyb
run WGR_Cubie.cmd
init cube bbgywbbroroowgwyygwwgorwygywoybbobrwrywgogrgbororybryg
run WGR_Cubie.cmd
init cube wroywboybgoybgwyyrggogrogrywwbwbrrgrywogorwbrwybbyogob
run WGR_Cubie.cmd
init cube orrgwwrrgbybggyrrywgwbrogyyogyybwbwgbwwbooybwrrobyogoo
run WGR_Cubie.cmd
init cube gbygwogbgwywogwwwborogroogwybrwbybwbgyrroyygbyrrryboor
run WGR_Cubie.cmd
init cube ywwbwyybogoooggggrbwgyrbwbbwrbybgywyorrooyoorbrrrygwwg
run WGR_Cubie.cmd
init cube ywogwobrggywygoyrbryowrwwwwygbgbyrogybrbooorborgbybrgw
run WGR_Cubie.cmd
init cube ggwywwoogobybgooyrgwygrrbbbrbgybgwgwrwwyorbwbyoooyryrr
run WGR_Cubie.cmd
init cube rroywbrgoggywgygwwbowrrobbybrbybbgbgygwyogooororrywyww
run WGR_Cubie.cmd
init cube rybgwoyyyyobogrwrbrbogrbwwrbwwwbrgbgrggyobyooogwwyrgyo
run WGR_Cubie.cmd
init cube rwobwyrgbyoywgogygbrogrbyrbwobybbrrwyrgwogrwwoywgyboog
run WGR_Cubie.cmd
init cube wggywbygyroorgbrwgbybrrwoobroorbbrgbyrgwoywbgwwwgyoyyo
run WGR_Cubie.cmd
init cube owgywbybrbbgbggbrgowbwryrywwrwobrroborwgooygyyggyywoor
run WGR_Cubie.cmd
init cube rowywgbbrgbrggwbyoyrbgrrgrywoowbwgwogywboyboyygrryoobw
run WGR_Cubie.cmd
init cube gwggwroobrrybgwobogwwgrobyrryrbbbbgowryyowyogwoyryywgb
run WGR_Cubie.cmd
init cube rbgywgoobgobbggrorywrorbyrwyywrbyorooywrowgwbggbbywwgy
run WGR_Cubie.cmd
init cube ygowwwrywbbyrgrrowbgbgryrroorgbbygorwwooobwoggyywybygb
run WGR_Cubie.cmd
init cube ogwrworygyygygrbwrygwwrowooobgwbrgrorwbbobborbgybygyyw
run WGR_Cubie.cmd
init cube bbgwwyogrygbbgyorryogorowggyrowbgwwwyyryowobgbrrbyrwob
run WGR_Cubie.cmd
init cube ogrbwbobbbogggbowowwwrrggywrygobyrgbyywoowyobyrgryrywr
run WGR_Cubie.cmd
init cube goybwwwywyobrgybbgoorbrwryrbrbbbgggwrwowoggoyyrwryyogo
run WGR_Cubie.cmd
init cube yrgwwyyrgbobggwgworbwrrwbyrooogbyyowyyoborbgrwggbybwor
run WGR_Cubie.cmd
init cube yoobwrybbgogbgoogwoyrgrwrobyygrbgrbowwrrowbwbgywyyrygw
run WGR_Cubie.cmd
init cube grorwoybywygbgywbgorborwrgrrwbgbowboywrgoybgoyrbwyogyw
run WGR_Cubie.cmd
init cube yowowwgoobwyggbbgbrbyyrrrybgbogbrybrgyowowgyowgroyrwrw
run WGR_Cubie.cmd
init cube gwybwrrobywyogywyybwwrrgbbgrbrobbogwggoooyrwboywgyrorg
run WGR_Cubie.cmd
init cube gyowwogboyoywggbbbrowyrbrrwbybrbrgggyrowogwwrwgoyyoybr
run WGR_Cubie.cmd
init cube woobworrroowbgwwoygbybrybrrbyygbwwwygwbgoygroogbgyrgyr
run WGR_Cubie.cmd
init cube robbwobwrwrrygywyoygwrrogbogyywbgwrrobboobywbywggygorg
run WGR_Cubie.cmd
init cube orogwbgwbgowggrbbrogyyryggyoowobbgwbbwywoyybwwrryyorrr
run WGR_Cubie.cmd