init cube yyyywrbwbrowggbogwrryorwooyoygbbygbrogbboogggbwrryrwww
run YBO_Cubie.cmd
init cube wogbwgywyoyoygwggybbrgrooywgrwbbwbrbowbrooyrrggroyywbr
run YBO_Cubie.cmd
init cube gobowwyryrgoygrbyobggwrbwgyobwrbyrogrwyoogwbogwbrybwyr
run YBO_Cubie.cmd
init cube yyrowbwwybygogrgwwrggbrbobboyywbrryrbrogogyowbowrygowg
run YBO_Cubie.cmd
init cube robrwbgoobbyygwrrwrgygryowggoybboogroyywogwwwbbwyyrgrb
run YBO_Cubie.cmd
init cube wwbrwoogbrbgrggbwowwyorrbyroywwbyyogrbgbogyrrwggoybyyo
run YBO_Cubie.cmd
init cube ggobwywowwrrrggbbobboyrgbgrgbyrbwyyrgorroybwywwgwyoooy
run YBO_Cubie.cmd
init cube ggyrwogbbyyybgowowrrybryrgboybbbrrwwrwogowgrbgywgyoowo
run YBO_Cubie.cmd
init cube bybbworyyrrgygboggybgwrwooroyrrbggwyyrwoogbwwwbwrygboo
run YBO_Cubie.cmd
init cube gowbwgbgrryrwgoowwyywwrwbrygobbbbbrgoyyrogyogrgoryywbo
run YBO_Cubie.cmd
init cube grbrwybobwwybggwwgowryroooyyrwgbwoygrbrboyrgbwbggyoory
run YBO_Cubie.cmd
init cube ooowwgbyygrryggwgryborrogbwbowwbwgbybyygorgwrwroyyobbr
run YBO_Cubie.cmd
init cube yrwbwgoobbygwgwygrwyogrbgwrwrrrbyyrobwogobgobwogoyyrby
run YBO_Cubie.cmd
init cube boyrwggwbywrrgorygwoygryorbowgbbywrgobrgoyrwbwbooygwby
run YBO_Cubie.cmd
init cube wwwywroogbggwgorogwbowrbwryygbybyrbyorroogbbgrybgyrywo
run YBO_Cubie.cmd
init cube yrybwgboybwoygwgbgwbborgwryrorybrowwgyowoobgwrbgyygorr
run YBO_Cubie.cmd
init cube borgwbbwgoyrggobroyoybrggyorrbwbgwywwyyroorwoybgwyrwbg
run YBO_Cubie.cmd
init cube gbybwgyywryoygrgwbboggrbrrwrobrbygworwygorboowwooygybw
run YBO_Cubie.cmd
init cube ggygwrogoryyrgbroogwgyrbbrrwyorbowoyboywogrwwwwbbyygbb
run YBO_Cubie.cmd
init cube bygbwybybywoggowoywgwyrogrwrrobbbrrbybrrowogorwgwyggoy
run YBO_Cubie.cmd
init cube yggrwowowbwoygwryrggborgwgrobowbygwryyoroobbgbrwbybyry
run YBO_Cubie.cmd
init cube ryrgwryywyrowgwrrybbbbryoowobbobwrowwgggorgoygggyywbbo
run YBO_Cubie.cmd
init cube ywwgwrywrrogbgyrorogworwybbgybrbyoooobbgoywrbgrywybwgg
run YBO_Cubie.cmd
init cube oywrwbwrgybobgbrooggywrwbrgryggbgywbrobyoorgywyowyrbow
run YBO_Cubie.cmd
init cube grwbwyrwyrowogrwyggbbgryyrwrrrobgowbbbyoowoboowbgyggyy
run YBO_Cubie.cmd
init cube wwwgwrgryrrwggbbywoboyrwbgybybobooorobgbooyrrrwggyyywg
run YBO_Cubie.cmd
init cube ggowwggyrybwwgwrbborgrrrogwyywbbobgwbroyoorbyyoryywbog
run YBO_Cubie.cmd
init cube orgowwryybbwggywrbgrooryygwboogbbgrrygwyooybrrwobywbwg
run YBO_Cubie.cmd
init cube goygwbgwoyrrygyyrowowrrbywrborwbrwgogyowobwgbbgbbyyrog
run YBO_Cubie.cmd
init cube owrowgrbrggbygowybwrwbrooyygwgwbyrwoyryrobbroyobgybggw
run YBO_Cubie.cmd
init cube rrwgwwyrryogbgyoyyogwbrrrwggorybwoobbbggoowrbbbwgyyywo
run YBO_Cubie.cmd
init cube robwwyggogrobgrowyywwgrgroobgwobbwrrrywroyyobbwgbyyybg
run YBO_Cubie.cmd
init cube bywwwyoroyggggwrbgwgbrrowywyobbbbbooorrwoygggrbrrywyoy
run YBO_Cubie.cmd
init cube wyrrwyoggbwybgrogbgrrbrgwwbwogybgywyyrrooybbgobrwyowoo
run YBO_Cubie.cmd
init cube rryywgoyywrwrgogwwborgrwggbgrbobbobgrwbwobyyroyygyowbo
run YBO_Cubie.cmd
init cube grrywbrrborbygbygowgoorryygwwybbywwgbwwboorggbgroyoowy
run YBO_Cubie.cmd
init cube oywgwbowgbwgbgobrywoybrrowbrrrgbryyrbgwyoygoygbrwyoogw
run YBO_Cubie.cmd
init cube rogwwbggobgorggbowyowyrgbrrbrwrboywwobywoyrbyrwgyyboyg
run YBO_Cubie.cmd
init cube oyygwgobwbogwgoowgwyryrowgrbrrbbrbryggwyoroobrwybybywg
run YBO_Cubie.cmd
init cube ogywwyoybwoyrgbogggbyrrgwbroobobgwbrrrgyowyrwrwbwyobyg
run YBO_Cubie.cmd
init cube oroowygwbbwwoggrybobworrywyrgyybgbgwgbwwobrygrrobyryog
run YBO_Cubie.cmd
init cube rorbwygrgbywbgrorrogrbryywbwobgbwwyywbyoowboyggowyrggo
run YBO_Cubie.cmd
init cube ygyrwowyogygogyrrbrgbbroygwybggbwoboowrooywwbrrbbywwrg
run YBO_Cubie.cmd
init cube ggbwwwbwyyowyggwyrrrbrrwyoorbogbrwrowooyooyyggbggybrbb
run YBO_Cubie.cmd
init cube wgyyworybgowwgrygwgrygrrogwobrbbbbrygooyooowbbyrwywrbg
run YBO_Cubie.cmd
init cube wwwywgyboboboggybyrywwrwoygbrorbbwyogoroogyrrggrwyrgbb
run YBO_Cubie.cmd
init cube bgoywowbryggrggoyorrbrrggwbwwgwbwwbyworroygybybobyoyor
run YBO_Cubie.cmd
init cube yrwrwowbobybogwbogorgbrgygrwyrwbyyrwbwobogroroygbygywg
run YBO_Cubie.cmd
init cube bwrowbwgwwgoogwybrgrgrrywgorogobygwryborowbyobyyrygbby
run YBO_Cubie.cmd
init cube rbrbwgyrrbyroggowbgwwyrbooygobrbrowowoygowbrgyyggybwyw
run YBO_Cubie.cmd
init cube byyrwgwbrrwbogygggorwbrgobbgyoobyywgbrwoowyoywwrrygrbo
run YBO_Cubie.cmd
init cube wogwwwyrwrobrgggbyryrorbgobbborbywgyyyggogbrwrboyywowo
run YBO_Cubie.cmd
init cube wrgwwobywboyygrobgoobgrrrwgobwybowwbowrgobyyyybrrygggr
run YBO_Cubie.cmd
init cube wwrrwbyobgwoygygyobwrorrbgyyrbgbyoogwborogrgrwogbybwwy
run YBO_Cubie.cmd
init cube rwyywwwggyrrbgobrybwrbryryywooobbooobrgyowwrobgggygwbg
run YBO_Cubie.cmd
init cube bwwowgbygygyrgbgyrobworogwboyrybrwrybgrwogooywborybrwg
run YBO_Cubie.cmd
init cube bwobwgrworowogoyrogggyrgyrbwryobrwyrgbwwowyybbboyygrbg
run YBO_Cubie.cmd
init cube ogwowgwrbygbbgwooooyrbrygwgyrrbbwwyrbwbroryogyoryygwbg
run YBO_Cubie.cmd
init cube rbrywybogwrowgrgoywyobrgbbgygyobgwggbobworoyyowrwyrrbw
run YBO_Cubie.cmd
init cube ryygwobbbbyygggrywooorrbrogwwrrbworogoybowgybggwrywwby
run YBO_Cubie.cmd
init cube yyrbwwwgyrwbogwgbrororroyggbobybgyowwbbwoggrrgyorybwyo
run YBO_Cubie.cmd
init cube gogrwwbrgrywrgbobwrbrorggyowoowbgyrbygyyowyowobbwygbyr
run YBO_Cubie.cmd
init cube wgyrwroyrrywogwggbbbborwybgwgrgbbowygogroybborowyyrywo
run YBO_Cubie.cmd
init cube ogroworbrbwwbggorogwbwryyoywyybbroyrbywwooyrgbgggyrwbg
run YBO_Cubie.cmd
init cube rowbwyobwbryygrbwrgobwryygworggbggbyryyoobbwwgrooywrgo
run YBO_Cubie.cmd
init cube grbrwybgrogoygbyggwwgrrgyrbyoroborbryywwobgboowwyywbow
run YBO_Cubie.cmd
init cube rwrowwwogggbrgbgrrowowrgbywygbrbygybwrwoobobyyboyygroy
run YBO_Cubie.cmd
init cube orggwbrywyowbgrbobgrrwrwyyobroobbwgyygbyowgoorggbywwyr
run YBO_Cubie.cmd
init cube ggbrworbwwwywgbygbbyorroogwgboybrbwrwrryobyggyyroyoowg
run YBO_Cubie.cmd
init cube wgrrwoobroyyogorrogwwgrowrygybwbybrywybbobrgggwogybywb
run YBO_Cubie.cmd
init cube boggwyogyoogogwrbgwwbrryyrbrryobyrrwrwygobobwobwwyggyb
run YBO_Cubie.cmd
init cube bbgywbbroroowgwyygwwgorwygywoybbobrwrywgogrgbororybryg
run YBO_Cubie.cmd
init cube wroywboybgoybgwyyrggogrogrywwbwbrrgrywogorwbrwybbyogob
run YBO_Cubie.cmd
init cube orrgwwrrgbybggyrrywgwbrogyyogyybwbwgbwwbooybwrrobyogoo
run YBO_Cubie.cmd
init cube gbygwogbgwywogwwwborogroogwybrwbybwbgyrroyygbyrrryboor
run YBO_Cubie.cmd
init cube ywwbwyybogoooggggrbwgyrbwbbwrbybgywyorrooyoorbrrrygwwg
run YBO_Cubie.cmd
init cube ywogwobrggywygoyrbryowrwwwwygbgbyrogybrbooorborgbybrgw
run YBO_Cubie.cmd
init cube ggwywwoogobybgooyrgwygrrbbbrbgybgwgwrwwyorbwbyoooyryrr
run YBO_Cubie.cmd
init cube rroywbrgoggywgygwwbowrrobbybrbybbgbgygwyogooororrywyww
run YBO_Cubie.cmd
init cube rybgwoyyyyobogrwrbrbogrbwwrbwwwbrgbgrggyobyooogwwyrgyo
run YBO_Cubie.cmd
init cube rwobwyrgbyoywgogygbrogrbyrbwobybbrrwyrgwogrwwoywgyboog
run YBO_Cubie.cmd
init cube wggywbygyroorgbrwgbybrrwoobroorbbrgbyrgwoywbgwwwgyoyyo
run YBO_Cubie.cmd
init cube owgywbybrbbgbggbrgowbwryrywwrwobrroborwgooygyyggyywoor
run YBO_Cubie.cmd
init cube rowywgbbrgbrggwbyoyrbgrrgrywoowbwgwogywboyboyygrryoobw
run YBO_Cubie.cmd
init cube gwggwroobrrybgwobogwwgrobyrryrbbbbgowryyowyogwoyryywgb
run YBO_Cubie.cmd
init cube rbgywgoobgobbggrorywrorbyrwyywrbyorooywrowgwbggbbywwgy
run YBO_Cubie.cmd
init cube ygowwwrywbbyrgrrowbgbgryrroorgbbygorwwooobwoggyywybygb
run YBO_Cubie.cmd
init cube ogwrworygyygygrbwrygwwrowooobgwbrgrorwbbobborbgybygyyw
run YBO_Cubie.cmd
init cube bbgwwyogrygbbgyorryogorowggyrowbgwwwyyryowobgbrrbyrwob
run YBO_Cubie.cmd
init cube ogrbwbobbbogggbowowwwrrggywrygobyrgbyywoowyobyrgryrywr
run YBO_Cubie.cmd
init cube goybwwwywyobrgybbgoorbrwryrbrbbbgggwrwowoggoyyrwryyogo
run YBO_Cubie.cmd
init cube yrgwwyyrgbobggwgworbwrrwbyrooogbyyowyyoborbgrwggbybwor
run YBO_Cubie.cmd
init cube yoobwrybbgogbgoogwoyrgrwrobyygrbgrbowwrrowbwbgywyyrygw
run YBO_Cubie.cmd
init cube grorwoybywygbgywbgorborwrgrrwbgbowboywrgoybgoyrbwyogyw
run YBO_Cubie.cmd
init cube yowowwgoobwyggbbgbrbyyrrrybgbogbrybrgyowowgyowgroyrwrw
run YBO_Cubie.cmd
init cube gwybwrrobywyogywyybwwrrgbbgrbrobbogwggoooyrwboywgyrorg
run YBO_Cubie.cmd
init cube gyowwogboyoywggbbbrowyrbrrwbybrbrgggyrowogwwrwgoyyoybr
run YBO_Cubie.cmd
init cube woobworrroowbgwwoygbybrybrrbyygbwwwygwbgoygroogbgyrgyr
run YBO_Cubie.cmd
init cube robbwobwrwrrygywyoygwrrogbogyywbgwrrobboobywbywggygorg
run YBO_Cubie.cmd
init cube orogwbgwbgowggrbbrogyyryggyoowobbgwbbwywoyybwwrryyorrr
run YBO_Cubie.cmd

