init cube yyyywrbwbrowggbogwrryorwooyoygbbygbrogbboogggbwrryrwww
run WRB_Cubie.cmd
init cube wogbwgywyoyoygwggybbrgrooywgrwbbwbrbowbrooyrrggroyywbr
run WRB_Cubie.cmd
init cube gobowwyryrgoygrbyobggwrbwgyobwrbyrogrwyoogwbogwbrybwyr
run WRB_Cubie.cmd
init cube yyrowbwwybygogrgwwrggbrbobboyywbrryrbrogogyowbowrygowg
run WRB_Cubie.cmd
init cube robrwbgoobbyygwrrwrgygryowggoybboogroyywogwwwbbwyyrgrb
run WRB_Cubie.cmd
init cube wwbrwoogbrbgrggbwowwyorrbyroywwbyyogrbgbogyrrwggoybyyo
run WRB_Cubie.cmd
init cube ggobwywowwrrrggbbobboyrgbgrgbyrbwyyrgorroybwywwgwyoooy
run WRB_Cubie.cmd
init cube ggyrwogbbyyybgowowrrybryrgboybbbrrwwrwogowgrbgywgyoowo
run WRB_Cubie.cmd
init cube bybbworyyrrgygboggybgwrwooroyrrbggwyyrwoogbwwwbwrygboo
run WRB_Cubie.cmd
init cube gowbwgbgrryrwgoowwyywwrwbrygobbbbbrgoyyrogyogrgoryywbo
run WRB_Cubie.cmd
init cube grbrwybobwwybggwwgowryroooyyrwgbwoygrbrboyrgbwbggyoory
run WRB_Cubie.cmd
init cube ooowwgbyygrryggwgryborrogbwbowwbwgbybyygorgwrwroyyobbr
run WRB_Cubie.cmd
init cube yrwbwgoobbygwgwygrwyogrbgwrwrrrbyyrobwogobgobwogoyyrby
run WRB_Cubie.cmd
init cube boyrwggwbywrrgorygwoygryorbowgbbywrgobrgoyrwbwbooygwby
run WRB_Cubie.cmd
init cube wwwywroogbggwgorogwbowrbwryygbybyrbyorroogbbgrybgyrywo
run WRB_Cubie.cmd
init cube yrybwgboybwoygwgbgwbborgwryrorybrowwgyowoobgwrbgyygorr
run WRB_Cubie.cmd
init cube borgwbbwgoyrggobroyoybrggyorrbwbgwywwyyroorwoybgwyrwbg
run WRB_Cubie.cmd
init cube gbybwgyywryoygrgwbboggrbrrwrobrbygworwygorboowwooygybw
run WRB_Cubie.cmd
init cube ggygwrogoryyrgbroogwgyrbbrrwyorbowoyboywogrwwwwbbyygbb
run WRB_Cubie.cmd
init cube bygbwybybywoggowoywgwyrogrwrrobbbrrbybrrowogorwgwyggoy
run WRB_Cubie.cmd
init cube yggrwowowbwoygwryrggborgwgrobowbygwryyoroobbgbrwbybyry
run WRB_Cubie.cmd
init cube ryrgwryywyrowgwrrybbbbryoowobbobwrowwgggorgoygggyywbbo
run WRB_Cubie.cmd
init cube ywwgwrywrrogbgyrorogworwybbgybrbyoooobbgoywrbgrywybwgg
run WRB_Cubie.cmd
init cube oywrwbwrgybobgbrooggywrwbrgryggbgywbrobyoorgywyowyrbow
run WRB_Cubie.cmd
init cube grwbwyrwyrowogrwyggbbgryyrwrrrobgowbbbyoowoboowbgyggyy
run WRB_Cubie.cmd
init cube wwwgwrgryrrwggbbywoboyrwbgybybobooorobgbooyrrrwggyyywg
run WRB_Cubie.cmd
init cube ggowwggyrybwwgwrbborgrrrogwyywbbobgwbroyoorbyyoryywbog
run WRB_Cubie.cmd
init cube orgowwryybbwggywrbgrooryygwboogbbgrrygwyooybrrwobywbwg
run WRB_Cubie.cmd
init cube goygwbgwoyrrygyyrowowrrbywrborwbrwgogyowobwgbbgbbyyrog
run WRB_Cubie.cmd
init cube owrowgrbrggbygowybwrwbrooyygwgwbyrwoyryrobbroyobgybggw
run WRB_Cubie.cmd
init cube rrwgwwyrryogbgyoyyogwbrrrwggorybwoobbbggoowrbbbwgyyywo
run WRB_Cubie.cmd
init cube robwwyggogrobgrowyywwgrgroobgwobbwrrrywroyyobbwgbyyybg
run WRB_Cubie.cmd
init cube bywwwyoroyggggwrbgwgbrrowywyobbbbbooorrwoygggrbrrywyoy
run WRB_Cubie.cmd
init cube wyrrwyoggbwybgrogbgrrbrgwwbwogybgywyyrrooybbgobrwyowoo
run WRB_Cubie.cmd
init cube rryywgoyywrwrgogwwborgrwggbgrbobbobgrwbwobyyroyygyowbo
run WRB_Cubie.cmd
init cube grrywbrrborbygbygowgoorryygwwybbywwgbwwboorggbgroyoowy
run WRB_Cubie.cmd
init cube oywgwbowgbwgbgobrywoybrrowbrrrgbryyrbgwyoygoygbrwyoogw
run WRB_Cubie.cmd
init cube rogwwbggobgorggbowyowyrgbrrbrwrboywwobywoyrbyrwgyyboyg
run WRB_Cubie.cmd
init cube oyygwgobwbogwgoowgwyryrowgrbrrbbrbryggwyoroobrwybybywg
run WRB_Cubie.cmd
init cube ogywwyoybwoyrgbogggbyrrgwbroobobgwbrrrgyowyrwrwbwyobyg
run WRB_Cubie.cmd
init cube oroowygwbbwwoggrybobworrywyrgyybgbgwgbwwobrygrrobyryog
run WRB_Cubie.cmd
init cube rorbwygrgbywbgrorrogrbryywbwobgbwwyywbyoowboyggowyrggo
run WRB_Cubie.cmd
init cube ygyrwowyogygogyrrbrgbbroygwybggbwoboowrooywwbrrbbywwrg
run WRB_Cubie.cmd
init cube ggbwwwbwyyowyggwyrrrbrrwyoorbogbrwrowooyooyyggbggybrbb
run WRB_Cubie.cmd
init cube wgyyworybgowwgrygwgrygrrogwobrbbbbrygooyooowbbyrwywrbg
run WRB_Cubie.cmd
init cube wwwywgyboboboggybyrywwrwoygbrorbbwyogoroogyrrggrwyrgbb
run WRB_Cubie.cmd
init cube bgoywowbryggrggoyorrbrrggwbwwgwbwwbyworroygybybobyoyor
run WRB_Cubie.cmd
init cube yrwrwowbobybogwbogorgbrgygrwyrwbyyrwbwobogroroygbygywg
run WRB_Cubie.cmd
init cube bwrowbwgwwgoogwybrgrgrrywgorogobygwryborowbyobyyrygbby
run WRB_Cubie.cmd
init cube rbrbwgyrrbyroggowbgwwyrbooygobrbrowowoygowbrgyyggybwyw
run WRB_Cubie.cmd
init cube byyrwgwbrrwbogygggorwbrgobbgyoobyywgbrwoowyoywwrrygrbo
run WRB_Cubie.cmd
init cube wogwwwyrwrobrgggbyryrorbgobbborbywgyyyggogbrwrboyywowo
run WRB_Cubie.cmd
init cube wrgwwobywboyygrobgoobgrrrwgobwybowwbowrgobyyyybrrygggr
run WRB_Cubie.cmd
init cube wwrrwbyobgwoygygyobwrorrbgyyrbgbyoogwborogrgrwogbybwwy
run WRB_Cubie.cmd
init cube rwyywwwggyrrbgobrybwrbryryywooobbooobrgyowwrobgggygwbg
run WRB_Cubie.cmd
init cube bwwowgbygygyrgbgyrobworogwboyrybrwrybgrwogooywborybrwg
run WRB_Cubie.cmd
init cube bwobwgrworowogoyrogggyrgyrbwryobrwyrgbwwowyybbboyygrbg
run WRB_Cubie.cmd
init cube ogwowgwrbygbbgwooooyrbrygwgyrrbbwwyrbwbroryogyoryygwbg
run WRB_Cubie.cmd
init cube rbrywybogwrowgrgoywyobrgbbgygyobgwggbobworoyyowrwyrrbw
run WRB_Cubie.cmd
init cube ryygwobbbbyygggrywooorrbrogwwrrbworogoybowgybggwrywwby
run WRB_Cubie.cmd
init cube yyrbwwwgyrwbogwgbrororroyggbobybgyowwbbwoggrrgyorybwyo
run WRB_Cubie.cmd
init cube gogrwwbrgrywrgbobwrbrorggyowoowbgyrbygyyowyowobbwygbyr
run WRB_Cubie.cmd
init cube wgyrwroyrrywogwggbbbborwybgwgrgbbowygogroybborowyyrywo
run WRB_Cubie.cmd
init cube ogroworbrbwwbggorogwbwryyoywyybbroyrbywwooyrgbgggyrwbg
run WRB_Cubie.cmd
init cube rowbwyobwbryygrbwrgobwryygworggbggbyryyoobbwwgrooywrgo
run WRB_Cubie.cmd
init cube grbrwybgrogoygbyggwwgrrgyrbyoroborbryywwobgboowwyywbow
run WRB_Cubie.cmd
init cube rwrowwwogggbrgbgrrowowrgbywygbrbygybwrwoobobyyboyygroy
run WRB_Cubie.cmd
init cube orggwbrywyowbgrbobgrrwrwyyobroobbwgyygbyowgoorggbywwyr
run WRB_Cubie.cmd
init cube ggbrworbwwwywgbygbbyorroogwgboybrbwrwrryobyggyyroyoowg
run WRB_Cubie.cmd
init cube wgrrwoobroyyogorrogwwgrowrygybwbybrywybbobrgggwogybywb
run WRB_Cubie.cmd
init cube boggwyogyoogogwrbgwwbrryyrbrryobyrrwrwygobobwobwwyggyb
run WRB_Cubie.cmd
init cube bbgywbbroroowgwyygwwgorwygywoybbobrwrywgogrgbororybryg
run WRB_Cubie.cmd
init cube wroywboybgoybgwyyrggogrogrywwbwbrrgrywogorwbrwybbyogob
run WRB_Cubie.cmd
init cube orrgwwrrgbybggyrrywgwbrogyyogyybwbwgbwwbooybwrrobyogoo
run WRB_Cubie.cmd
init cube gbygwogbgwywogwwwborogroogwybrwbybwbgyrroyygbyrrryboor
run WRB_Cubie.cmd
init cube ywwbwyybogoooggggrbwgyrbwbbwrbybgywyorrooyoorbrrrygwwg
run WRB_Cubie.cmd
init cube ywogwobrggywygoyrbryowrwwwwygbgbyrogybrbooorborgbybrgw
run WRB_Cubie.cmd
init cube ggwywwoogobybgooyrgwygrrbbbrbgybgwgwrwwyorbwbyoooyryrr
run WRB_Cubie.cmd
init cube rroywbrgoggywgygwwbowrrobbybrbybbgbgygwyogooororrywyww
run WRB_Cubie.cmd
init cube rybgwoyyyyobogrwrbrbogrbwwrbwwwbrgbgrggyobyooogwwyrgyo
run WRB_Cubie.cmd
init cube rwobwyrgbyoywgogygbrogrbyrbwobybbrrwyrgwogrwwoywgyboog
run WRB_Cubie.cmd
init cube wggywbygyroorgbrwgbybrrwoobroorbbrgbyrgwoywbgwwwgyoyyo
run WRB_Cubie.cmd
init cube owgywbybrbbgbggbrgowbwryrywwrwobrroborwgooygyyggyywoor
run WRB_Cubie.cmd
init cube rowywgbbrgbrggwbyoyrbgrrgrywoowbwgwogywboyboyygrryoobw
run WRB_Cubie.cmd
init cube gwggwroobrrybgwobogwwgrobyrryrbbbbgowryyowyogwoyryywgb
run WRB_Cubie.cmd
init cube rbgywgoobgobbggrorywrorbyrwyywrbyorooywrowgwbggbbywwgy
run WRB_Cubie.cmd
init cube ygowwwrywbbyrgrrowbgbgryrroorgbbygorwwooobwoggyywybygb
run WRB_Cubie.cmd
init cube ogwrworygyygygrbwrygwwrowooobgwbrgrorwbbobborbgybygyyw
run WRB_Cubie.cmd
init cube bbgwwyogrygbbgyorryogorowggyrowbgwwwyyryowobgbrrbyrwob
run WRB_Cubie.cmd
init cube ogrbwbobbbogggbowowwwrrggywrygobyrgbyywoowyobyrgryrywr
run WRB_Cubie.cmd
init cube goybwwwywyobrgybbgoorbrwryrbrbbbgggwrwowoggoyyrwryyogo
run WRB_Cubie.cmd
init cube yrgwwyyrgbobggwgworbwrrwbyrooogbyyowyyoborbgrwggbybwor
run WRB_Cubie.cmd
init cube yoobwrybbgogbgoogwoyrgrwrobyygrbgrbowwrrowbwbgywyyrygw
run WRB_Cubie.cmd
init cube grorwoybywygbgywbgorborwrgrrwbgbowboywrgoybgoyrbwyogyw
run WRB_Cubie.cmd
init cube yowowwgoobwyggbbgbrbyyrrrybgbogbrybrgyowowgyowgroyrwrw
run WRB_Cubie.cmd
init cube gwybwrrobywyogywyybwwrrgbbgrbrobbogwggoooyrwboywgyrorg
run WRB_Cubie.cmd
init cube gyowwogboyoywggbbbrowyrbrrwbybrbrgggyrowogwwrwgoyyoybr
run WRB_Cubie.cmd
init cube woobworrroowbgwwoygbybrybrrbyygbwwwygwbgoygroogbgyrgyr
run WRB_Cubie.cmd
init cube robbwobwrwrrygywyoygwrrogbogyywbgwrrobboobywbywggygorg
run WRB_Cubie.cmd
init cube orogwbgwbgowggrbbrogyyryggyoowobbgwbbwywoyybwwrryyorrr
run WRB_Cubie.cmd
