echo ------------------init cube---------------
init cube yyyywrbwbrowggbogwrryorwooyoygbbygbrogbboogggbwrryrwww
run WBO_Cubie.cmd
init cube wogbwgywyoyoygwggybbrgrooywgrwbbwbrbowbrooyrrggroyywbr
run WBO_Cubie.cmd
init cube gobowwyryrgoygrbyobggwrbwgyobwrbyrogrwyoogwbogwbrybwyr
run WBO_Cubie.cmd
init cube yyrowbwwybygogrgwwrggbrbobboyywbrryrbrogogyowbowrygowg
run WBO_Cubie.cmd
init cube robrwbgoobbyygwrrwrgygryowggoybboogroyywogwwwbbwyyrgrb
run WBO_Cubie.cmd
init cube wwbrwoogbrbgrggbwowwyorrbyroywwbyyogrbgbogyrrwggoybyyo
run WBO_Cubie.cmd
init cube ggobwywowwrrrggbbobboyrgbgrgbyrbwyyrgorroybwywwgwyoooy
run WBO_Cubie.cmd
init cube ggyrwogbbyyybgowowrrybryrgboybbbrrwwrwogowgrbgywgyoowo
run WBO_Cubie.cmd
init cube bybbworyyrrgygboggybgwrwooroyrrbggwyyrwoogbwwwbwrygboo
run WBO_Cubie.cmd
init cube gowbwgbgrryrwgoowwyywwrwbrygobbbbbrgoyyrogyogrgoryywbo
run WBO_Cubie.cmd
init cube grbrwybobwwybggwwgowryroooyyrwgbwoygrbrboyrgbwbggyoory
run WBO_Cubie.cmd
init cube ooowwgbyygrryggwgryborrogbwbowwbwgbybyygorgwrwroyyobbr
run WBO_Cubie.cmd
init cube yrwbwgoobbygwgwygrwyogrbgwrwrrrbyyrobwogobgobwogoyyrby
run WBO_Cubie.cmd
init cube boyrwggwbywrrgorygwoygryorbowgbbywrgobrgoyrwbwbooygwby
run WBO_Cubie.cmd
init cube wwwywroogbggwgorogwbowrbwryygbybyrbyorroogbbgrybgyrywo
run WBO_Cubie.cmd
init cube yrybwgboybwoygwgbgwbborgwryrorybrowwgyowoobgwrbgyygorr
run WBO_Cubie.cmd
init cube borgwbbwgoyrggobroyoybrggyorrbwbgwywwyyroorwoybgwyrwbg
run WBO_Cubie.cmd
init cube gbybwgyywryoygrgwbboggrbrrwrobrbygworwygorboowwooygybw
run WBO_Cubie.cmd
init cube ggygwrogoryyrgbroogwgyrbbrrwyorbowoyboywogrwwwwbbyygbb
run WBO_Cubie.cmd
init cube bygbwybybywoggowoywgwyrogrwrrobbbrrbybrrowogorwgwyggoy
run WBO_Cubie.cmd
init cube yggrwowowbwoygwryrggborgwgrobowbygwryyoroobbgbrwbybyry
run WBO_Cubie.cmd
init cube ryrgwryywyrowgwrrybbbbryoowobbobwrowwgggorgoygggyywbbo
run WBO_Cubie.cmd
init cube ywwgwrywrrogbgyrorogworwybbgybrbyoooobbgoywrbgrywybwgg
run WBO_Cubie.cmd
init cube oywrwbwrgybobgbrooggywrwbrgryggbgywbrobyoorgywyowyrbow
run WBO_Cubie.cmd
init cube grwbwyrwyrowogrwyggbbgryyrwrrrobgowbbbyoowoboowbgyggyy
run WBO_Cubie.cmd
init cube wwwgwrgryrrwggbbywoboyrwbgybybobooorobgbooyrrrwggyyywg
run WBO_Cubie.cmd
init cube ggowwggyrybwwgwrbborgrrrogwyywbbobgwbroyoorbyyoryywbog
run WBO_Cubie.cmd
init cube orgowwryybbwggywrbgrooryygwboogbbgrrygwyooybrrwobywbwg
run WBO_Cubie.cmd
init cube goygwbgwoyrrygyyrowowrrbywrborwbrwgogyowobwgbbgbbyyrog
run WBO_Cubie.cmd
init cube owrowgrbrggbygowybwrwbrooyygwgwbyrwoyryrobbroyobgybggw
run WBO_Cubie.cmd
init cube rrwgwwyrryogbgyoyyogwbrrrwggorybwoobbbggoowrbbbwgyyywo
run WBO_Cubie.cmd
init cube robwwyggogrobgrowyywwgrgroobgwobbwrrrywroyyobbwgbyyybg
run WBO_Cubie.cmd
init cube bywwwyoroyggggwrbgwgbrrowywyobbbbbooorrwoygggrbrrywyoy
run WBO_Cubie.cmd
init cube wyrrwyoggbwybgrogbgrrbrgwwbwogybgywyyrrooybbgobrwyowoo
run WBO_Cubie.cmd
init cube rryywgoyywrwrgogwwborgrwggbgrbobbobgrwbwobyyroyygyowbo
run WBO_Cubie.cmd
init cube grrywbrrborbygbygowgoorryygwwybbywwgbwwboorggbgroyoowy
run WBO_Cubie.cmd
init cube oywgwbowgbwgbgobrywoybrrowbrrrgbryyrbgwyoygoygbrwyoogw
run WBO_Cubie.cmd
init cube rogwwbggobgorggbowyowyrgbrrbrwrboywwobywoyrbyrwgyyboyg
run WBO_Cubie.cmd
init cube oyygwgobwbogwgoowgwyryrowgrbrrbbrbryggwyoroobrwybybywg
run WBO_Cubie.cmd
init cube ogywwyoybwoyrgbogggbyrrgwbroobobgwbrrrgyowyrwrwbwyobyg
run WBO_Cubie.cmd
init cube oroowygwbbwwoggrybobworrywyrgyybgbgwgbwwobrygrrobyryog
run WBO_Cubie.cmd
init cube rorbwygrgbywbgrorrogrbryywbwobgbwwyywbyoowboyggowyrggo
run WBO_Cubie.cmd
init cube ygyrwowyogygogyrrbrgbbroygwybggbwoboowrooywwbrrbbywwrg
run WBO_Cubie.cmd
init cube ggbwwwbwyyowyggwyrrrbrrwyoorbogbrwrowooyooyyggbggybrbb
run WBO_Cubie.cmd
init cube wgyyworybgowwgrygwgrygrrogwobrbbbbrygooyooowbbyrwywrbg
run WBO_Cubie.cmd
init cube wwwywgyboboboggybyrywwrwoygbrorbbwyogoroogyrrggrwyrgbb
run WBO_Cubie.cmd
init cube bgoywowbryggrggoyorrbrrggwbwwgwbwwbyworroygybybobyoyor
run WBO_Cubie.cmd
init cube yrwrwowbobybogwbogorgbrgygrwyrwbyyrwbwobogroroygbygywg
run WBO_Cubie.cmd
init cube bwrowbwgwwgoogwybrgrgrrywgorogobygwryborowbyobyyrygbby
run WBO_Cubie.cmd
init cube rbrbwgyrrbyroggowbgwwyrbooygobrbrowowoygowbrgyyggybwyw
run WBO_Cubie.cmd
init cube byyrwgwbrrwbogygggorwbrgobbgyoobyywgbrwoowyoywwrrygrbo
run WBO_Cubie.cmd
init cube wogwwwyrwrobrgggbyryrorbgobbborbywgyyyggogbrwrboyywowo
run WBO_Cubie.cmd
init cube wrgwwobywboyygrobgoobgrrrwgobwybowwbowrgobyyyybrrygggr
run WBO_Cubie.cmd
init cube wwrrwbyobgwoygygyobwrorrbgyyrbgbyoogwborogrgrwogbybwwy
run WBO_Cubie.cmd
init cube rwyywwwggyrrbgobrybwrbryryywooobbooobrgyowwrobgggygwbg
run WBO_Cubie.cmd
init cube bwwowgbygygyrgbgyrobworogwboyrybrwrybgrwogooywborybrwg
run WBO_Cubie.cmd
init cube bwobwgrworowogoyrogggyrgyrbwryobrwyrgbwwowyybbboyygrbg
run WBO_Cubie.cmd
init cube ogwowgwrbygbbgwooooyrbrygwgyrrbbwwyrbwbroryogyoryygwbg
run WBO_Cubie.cmd
init cube rbrywybogwrowgrgoywyobrgbbgygyobgwggbobworoyyowrwyrrbw
run WBO_Cubie.cmd
init cube ryygwobbbbyygggrywooorrbrogwwrrbworogoybowgybggwrywwby
run WBO_Cubie.cmd
init cube yyrbwwwgyrwbogwgbrororroyggbobybgyowwbbwoggrrgyorybwyo
run WBO_Cubie.cmd
init cube gogrwwbrgrywrgbobwrbrorggyowoowbgyrbygyyowyowobbwygbyr
run WBO_Cubie.cmd
init cube wgyrwroyrrywogwggbbbborwybgwgrgbbowygogroybborowyyrywo
run WBO_Cubie.cmd
init cube ogroworbrbwwbggorogwbwryyoywyybbroyrbywwooyrgbgggyrwbg
run WBO_Cubie.cmd
init cube rowbwyobwbryygrbwrgobwryygworggbggbyryyoobbwwgrooywrgo
run WBO_Cubie.cmd
init cube grbrwybgrogoygbyggwwgrrgyrbyoroborbryywwobgboowwyywbow
run WBO_Cubie.cmd
init cube rwrowwwogggbrgbgrrowowrgbywygbrbygybwrwoobobyyboyygroy
run WBO_Cubie.cmd
init cube orggwbrywyowbgrbobgrrwrwyyobroobbwgyygbyowgoorggbywwyr
run WBO_Cubie.cmd
init cube ggbrworbwwwywgbygbbyorroogwgboybrbwrwrryobyggyyroyoowg
run WBO_Cubie.cmd
init cube wgrrwoobroyyogorrogwwgrowrygybwbybrywybbobrgggwogybywb
run WBO_Cubie.cmd
init cube boggwyogyoogogwrbgwwbrryyrbrryobyrrwrwygobobwobwwyggyb
run WBO_Cubie.cmd
init cube bbgywbbroroowgwyygwwgorwygywoybbobrwrywgogrgbororybryg
run WBO_Cubie.cmd
init cube wroywboybgoybgwyyrggogrogrywwbwbrrgrywogorwbrwybbyogob
run WBO_Cubie.cmd
init cube orrgwwrrgbybggyrrywgwbrogyyogyybwbwgbwwbooybwrrobyogoo
run WBO_Cubie.cmd
init cube gbygwogbgwywogwwwborogroogwybrwbybwbgyrroyygbyrrryboor
run WBO_Cubie.cmd
init cube ywwbwyybogoooggggrbwgyrbwbbwrbybgywyorrooyoorbrrrygwwg
run WBO_Cubie.cmd
init cube ywogwobrggywygoyrbryowrwwwwygbgbyrogybrbooorborgbybrgw
run WBO_Cubie.cmd
init cube ggwywwoogobybgooyrgwygrrbbbrbgybgwgwrwwyorbwbyoooyryrr
run WBO_Cubie.cmd
init cube rroywbrgoggywgygwwbowrrobbybrbybbgbgygwyogooororrywyww
run WBO_Cubie.cmd
init cube rybgwoyyyyobogrwrbrbogrbwwrbwwwbrgbgrggyobyooogwwyrgyo
run WBO_Cubie.cmd
init cube rwobwyrgbyoywgogygbrogrbyrbwobybbrrwyrgwogrwwoywgyboog
run WBO_Cubie.cmd
init cube wggywbygyroorgbrwgbybrrwoobroorbbrgbyrgwoywbgwwwgyoyyo
run WBO_Cubie.cmd
init cube owgywbybrbbgbggbrgowbwryrywwrwobrroborwgooygyyggyywoor
run WBO_Cubie.cmd
init cube rowywgbbrgbrggwbyoyrbgrrgrywoowbwgwogywboyboyygrryoobw
run WBO_Cubie.cmd
init cube gwggwroobrrybgwobogwwgrobyrryrbbbbgowryyowyogwoyryywgb
run WBO_Cubie.cmd
init cube rbgywgoobgobbggrorywrorbyrwyywrbyorooywrowgwbggbbywwgy
run WBO_Cubie.cmd
init cube ygowwwrywbbyrgrrowbgbgryrroorgbbygorwwooobwoggyywybygb
run WBO_Cubie.cmd
init cube ogwrworygyygygrbwrygwwrowooobgwbrgrorwbbobborbgybygyyw
run WBO_Cubie.cmd
init cube bbgwwyogrygbbgyorryogorowggyrowbgwwwyyryowobgbrrbyrwob
run WBO_Cubie.cmd
init cube ogrbwbobbbogggbowowwwrrggywrygobyrgbyywoowyobyrgryrywr
run WBO_Cubie.cmd
init cube goybwwwywyobrgybbgoorbrwryrbrbbbgggwrwowoggoyyrwryyogo
run WBO_Cubie.cmd
init cube yrgwwyyrgbobggwgworbwrrwbyrooogbyyowyyoborbgrwggbybwor
run WBO_Cubie.cmd
init cube yoobwrybbgogbgoogwoyrgrwrobyygrbgrbowwrrowbwbgywyyrygw
run WBO_Cubie.cmd
init cube grorwoybywygbgywbgorborwrgrrwbgbowboywrgoybgoyrbwyogyw
run WBO_Cubie.cmd
init cube yowowwgoobwyggbbgbrbyyrrrybgbogbrybrgyowowgyowgroyrwrw
run WBO_Cubie.cmd
init cube gwybwrrobywyogywyybwwrrgbbgrbrobbogwggoooyrwboywgyrorg
run WBO_Cubie.cmd
init cube gyowwogboyoywggbbbrowyrbrrwbybrbrgggyrowogwwrwgoyyoybr
run WBO_Cubie.cmd
init cube woobworrroowbgwwoygbybrybrrbyygbwwwygwbgoygroogbgyrgyr
run WBO_Cubie.cmd
init cube robbwobwrwrrygywyoygwrrogbogyywbgwrrobboobywbywggygorg
run WBO_Cubie.cmd
init cube orogwbgwbgowggrbbrogyyryggyoowobbgwbbwywoyybwwrryyorrr
run WBO_Cubie.cmd