init cube ooowwgbyygrryggwgryborrogbwbowwbwgbybyygorgwrwroyyobbr
run StepByStepSearch.cmd
init cube yrwbwgoobbygwgwygrwyogrbgwrwrrrbyyrobwogobgobwogoyyrby
run StepByStepSearch.cmd
init cube boyrwggwbywrrgorygwoygryorbowgbbywrgobrgoyrwbwbooygwby
run StepByStepSearch.cmd
init cube wwwywroogbggwgorogwbowrbwryygbybyrbyorroogbbgrybgyrywo
run StepByStepSearch.cmd
init cube yrybwgboybwoygwgbgwbborgwryrorybrowwgyowoobgwrbgyygorr
run StepByStepSearch.cmd
init cube borgwbbwgoyrggobroyoybrggyorrbwbgwywwyyroorwoybgwyrwbg
run StepByStepSearch.cmd
init cube gbybwgyywryoygrgwbboggrbrrwrobrbygworwygorboowwooygybw
run StepByStepSearch.cmd
init cube ggygwrogoryyrgbroogwgyrbbrrwyorbowoyboywogrwwwwbbyygbb
run StepByStepSearch.cmd
init cube bygbwybybywoggowoywgwyrogrwrrobbbrrbybrrowogorwgwyggoy
run StepByStepSearch.cmd
init cube yggrwowowbwoygwryrggborgwgrobowbygwryyoroobbgbrwbybyry
run StepByStepSearch.cmd
init cube ryrgwryywyrowgwrrybbbbryoowobbobwrowwgggorgoygggyywbbo
run StepByStepSearch.cmd
init cube ywwgwrywrrogbgyrorogworwybbgybrbyoooobbgoywrbgrywybwgg
run StepByStepSearch.cmd
init cube oywrwbwrgybobgbrooggywrwbrgryggbgywbrobyoorgywyowyrbow
run StepByStepSearch.cmd
init cube byyrwgwbrrwbogygggorwbrgobbgyoobyywgbrwoowyoywwrrygrbo
run StepByStepSearch.cmd