init cube grwbwyrwyrowogrwyggbbgryyrwrrrobgowbbbyoowoboowbgyggyy
run StepByStepSearch.cmd
init cube wwwgwrgryrrwggbbywoboyrwbgybybobooorobgbooyrrrwggyyywg
run StepByStepSearch.cmd
init cube ggowwggyrybwwgwrbborgrrrogwyywbbobgwbroyoorbyyoryywbog
run StepByStepSearch.cmd
init cube orgowwryybbwggywrbgrooryygwboogbbgrrygwyooybrrwobywbwg
run StepByStepSearch.cmd
init cube goygwbgwoyrrygyyrowowrrbywrborwbrwgogyowobwgbbgbbyyrog
run StepByStepSearch.cmd
init cube owrowgrbrggbygowybwrwbrooyygwgwbyrwoyryrobbroyobgybggw
run StepByStepSearch.cmd
init cube rrwgwwyrryogbgyoyyogwbrrrwggorybwoobbbggoowrbbbwgyyywo
run StepByStepSearch.cmd
init cube robwwyggogrobgrowyywwgrgroobgwobbwrrrywroyyobbwgbyyybg
run StepByStepSearch.cmd
init cube bywwwyoroyggggwrbgwgbrrowywyobbbbbooorrwoygggrbrrywyoy
run StepByStepSearch.cmd
init cube wyrrwyoggbwybgrogbgrrbrgwwbwogybgywyyrrooybbgobrwyowoo
run StepByStepSearch.cmd
init cube rryywgoyywrwrgogwwborgrwggbgrbobbobgrwbwobyyroyygyowbo
run StepByStepSearch.cmd
init cube grrywbrrborbygbygowgoorryygwwybbywwgbwwboorggbgroyoowy
run StepByStepSearch.cmd
