init cube ywogwobrggywygoyrbryowrwwwwygbgbyrogybrbooorborgbybrgw
run StepByStepSearch.cmd
init cube ggwywwoogobybgooyrgwygrrbbbrbgybgwgwrwwyorbwbyoooyryrr
run StepByStepSearch.cmd
init cube rroywbrgoggywgygwwbowrrobbybrbybbgbgygwyogooororrywyww
run StepByStepSearch.cmd
init cube rybgwoyyyyobogrwrbrbogrbwwrbwwwbrgbgrggyobyooogwwyrgyo
run StepByStepSearch.cmd
init cube rwobwyrgbyoywgogygbrogrbyrbwobybbrrwyrgwogrwwoywgyboog
run StepByStepSearch.cmd
init cube wggywbygyroorgbrwgbybrrwoobroorbbrgbyrgwoywbgwwwgyoyyo
run StepByStepSearch.cmd
init cube owgywbybrbbgbggbrgowbwryrywwrwobrroborwgooygyyggyywoor
run StepByStepSearch.cmd
init cube rowywgbbrgbrggwbyoyrbgrrgrywoowbwgwogywboyboyygrryoobw
run StepByStepSearch.cmd
init cube gwggwroobrrybgwobogwwgrobyrryrbbbbgowryyowyogwoyryywgb
run StepByStepSearch.cmd
init cube rbgywgoobgobbggrorywrorbyrwyywrbyorooywrowgwbggbbywwgy
run StepByStepSearch.cmd
init cube ygowwwrywbbyrgrrowbgbgryrroorgbbygorwwooobwoggyywybygb
run StepByStepSearch.cmd
init cube ogwrworygyygygrbwrygwwrowooobgwbrgrorwbbobborbgybygyyw
run StepByStepSearch.cmd
init cube bbgwwyogrygbbgyorryogorowggyrowbgwwwyyryowobgbrrbyrwob
run StepByStepSearch.cmd
