init cube rowbwyobwbryygrbwrgobwryygworggbggbyryyoobbwwgrooywrgo
run StepByStepSearch.cmd
init cube grbrwybgrogoygbyggwwgrrgyrbyoroborbryywwobgboowwyywbow
run StepByStepSearch.cmd
init cube rwrowwwogggbrgbgrrowowrgbywygbrbygybwrwoobobyyboyygroy
run StepByStepSearch.cmd
init cube orggwbrywyowbgrbobgrrwrwyyobroobbwgyygbyowgoorggbywwyr
run StepByStepSearch.cmd
init cube ggbrworbwwwywgbygbbyorroogwgboybrbwrwrryobyggyyroyoowg
run StepByStepSearch.cmd
init cube wgrrwoobroyyogorrogwwgrowrygybwbybrywybbobrgggwogybywb
run StepByStepSearch.cmd
init cube boggwyogyoogogwrbgwwbrryyrbrryobyrrwrwygobobwobwwyggyb
run StepByStepSearch.cmd
init cube bbgywbbroroowgwyygwwgorwygywoybbobrwrywgogrgbororybryg
run StepByStepSearch.cmd
init cube wroywboybgoybgwyyrggogrogrywwbwbrrgrywogorwbrwybbyogob
run StepByStepSearch.cmd
init cube orrgwwrrgbybggyrrywgwbrogyyogyybwbwgbwwbooybwrrobyogoo
run StepByStepSearch.cmd
init cube gbygwogbgwywogwwwborogroogwybrwbybwbgyrroyygbyrrryboor
run StepByStepSearch.cmd
init cube ywwbwyybogoooggggrbwgyrbwbbwrbybgywyorrooyoorbrrrygwwg
run StepByStepSearch.cmd